name: Android CI

# Controls when the action will run.
on:
  pull_request:
    branches:
    - 'master'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest
    steps:
      # checkout
      - uses: actions/checkout@v1
      # setup jdk
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      # Make gradlew executable
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # run detekt
      - name: Run detekt
        run: ./gradlew detekt

      - name: Run some unit tests
        run: ./gradlew test

      - name: Run UI Tests
        uses: ReactiveCircus/android-emulator-runner@v2.15.0
        with:
          api-level: 29
          script: ./gradlew connectedCheck

      - name: Build with Gradle
        run: ./gradlew assembleDebug